/**
 * report.js — Printable calculation report with traceability
 *
 * REPORT.print(spec) builds a formal, print-only report (header with timestamp
 * and database version, input parameters, results, method, data sources and
 * disclaimer) and opens the browser print dialog. The report node is removed
 * after printing; the screen layout is untouched.
 *
 * spec = {
 *   title:    'External Dose Estimate',         // report heading
 *   nuclide:  { id, name, half_life_display, source, _icrp107 },
 *   sections: [ { heading, rows: [[label, value], ...] }, ... ],
 *   notes:    [ 'method / warning strings', ... ],
 *   sources:  [ 'reference strings', ... ],     // appended to the common ones
 * }
 *
 * All values are rendered as escaped text — pass plain strings.
 */

'use strict';

const REPORT = (() => {

  const COMMON_SOURCES = [
    'ICRP Publication 107 (2008) — Nuclear Decay Data for Dosimetric Calculations.',
    'ICRU Report 57 / ICRP Publication 74 (1996) — Conversion coefficients H*(10), H\'(0.07).',
    'Cornejo Díaz N., Brosed Serreta A., Ruiz Manzano P. (2015) — Constantes de tasa de kerma en aire y de dosis. Radioprotección Nº 83.',
  ];

  const DISCLAIMER =
    'Point-source estimate for radiation protection planning. Geometry, scatter, build-up and ' +
    'source-distribution effects are not modelled unless stated. NOT valid for patient dosimetry or ' +
    'treatment planning. Results must be reviewed by a qualified medical physics / radiation ' +
    'protection expert before regulatory or clinical use. Generated by NM Radionuclide Planner, an ' +
    'open-source reference tool provided without warranty of any kind.';

  function esc(s) {
    return String(s ?? '—')
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  /**
   * Per-nuclide data status for the report header.
   *
   * This used to print "Curated database entry (validated against published
   * sources)" for EVERY curated entry — including the Y-90 container estimates,
   * which have no primary source at all, and Ra-223, whose constant sits ~6%
   * from the published one. A signed, printed report must not overstate what was
   * actually checked (audit 2026-07-15, finding 6), so the status is now derived
   * per nuclide from the provenance already stored in nuclides.json.
   *
   * @param {object} n - nuclide record
   * @returns {string}
   */
  function validationStatus(n) {
    if (n.id === 'Y-90') {
      return 'ESTIMATE, no primary source — container bremsstrahlung constants follow the Zanzonico et al. (1999) methodology, but that publication tabulates soft tissue and bone only, not these container geometries. Not validated; no regulatory verdict is issued for this nuclide';
    }
    if (n._icrp107) {
      return 'ICRP 107 extended entry — constants computed from the ICRP 107 photon spectrum, NOT manually validated against a published constant';
    }
    const cv = n.cornejo_validation;
    const published = cv && cv.gamma_H10_Cornejo;
    if (published && Number.isFinite(n.gamma_H10)) {
      const dev = 100 * (n.gamma_H10 - published) / published;
      const sign = dev >= 0 ? '+' : '−';
      const agrees = Math.abs(dev) <= 2;
      return `Curated entry, cross-checked against ${cv.source || 'Cornejo et al. (2015)'}: published Γ^H*(10) = ${published}, stored ${n.gamma_H10} (${sign}${Math.abs(dev).toFixed(1)}%)`
        + (agrees ? '' : ' — the difference reflects updated ICRP 107 decay data and has NOT been reconciled with the published value');
    }
    return 'Curated entry computed from ICRP 107 photon data with ICRU 57 coefficients — no published reference constant exists to cross-check it against';
  }

  function buildHtml(spec) {
    const meta = (typeof DB !== 'undefined' && DB.getMeta) ? DB.getMeta() : {};
    const now  = new Date();
    const ts   = now.toISOString().slice(0, 16).replace('T', ' ') + ' (local: ' + now.toLocaleString() + ')';
    const n    = spec.nuclide || {};
    const validationTag = validationStatus(n);

    let html = `
      <div class="rpt-header">
        <div class="rpt-title">&#9762; NM Radionuclide Planner — ${esc(spec.title)}</div>
        <table class="rpt-meta">
          <tr><td>Generated</td><td>${esc(ts)}</td></tr>
          <tr><td>Database</td><td>nuclides.json v${esc(meta.version || '?')} — ${esc(meta.reference ? String(meta.reference).slice(0, 90) : '')}&hellip;</td></tr>
          <tr><td>Nuclide</td><td><strong>${esc(n.id)}</strong> — ${esc(n.name)} (T&#189; = ${esc(n.half_life_display)})</td></tr>
          <tr><td>Data status</td><td>${esc(validationTag)}</td></tr>
          ${n.source ? `<tr><td>Nuclide source</td><td>${esc(n.source)}</td></tr>` : ''}
        </table>
      </div>`;

    for (const sec of spec.sections || []) {
      html += `<div class="rpt-section"><div class="rpt-heading">${esc(sec.heading)}</div><table class="rpt-table">`;
      for (const [k, v] of sec.rows || []) {
        html += `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`;
      }
      html += `</table></div>`;
    }

    if (spec.notes && spec.notes.length) {
      html += `<div class="rpt-section"><div class="rpt-heading">Method &amp; warnings</div><ul class="rpt-list">`;
      for (const note of spec.notes) html += `<li>${esc(note)}</li>`;
      html += `</ul></div>`;
    }

    html += `<div class="rpt-section"><div class="rpt-heading">Data sources</div><ul class="rpt-list">`;
    for (const src of COMMON_SOURCES.concat(spec.sources || [])) html += `<li>${esc(src)}</li>`;
    html += `</ul></div>`;

    html += `
      <div class="rpt-disclaimer"><strong>Disclaimer.</strong> ${esc(DISCLAIMER)}</div>
      <div class="rpt-sign">
        <div>Reviewed by (name / signature): ______________________________</div>
        <div>Date: ____________</div>
      </div>`;

    return html;
  }

  function print(spec) {
    const old = document.getElementById('printReport');
    if (old) old.remove();
    const div = document.createElement('div');
    div.id = 'printReport';
    div.innerHTML = buildHtml(spec);
    document.body.appendChild(div);
    document.body.classList.add('print-report-mode');

    const cleanup = () => {
      document.body.classList.remove('print-report-mode');
      div.remove();
      window.removeEventListener('afterprint', cleanup);
    };
    window.addEventListener('afterprint', cleanup);
    window.print();
    // Safari/file:// may not fire afterprint reliably — defensive cleanup
    setTimeout(cleanup, 2000);
  }

  return { print };

})();
