#!/usr/bin/env node

/**
 * generate-data.js — Wrap the JSON data files as JavaScript for offline compatibility
 *
 * Reads each JSON source in data/ and writes its JS twin, which declares a
 * global constant loaded through a <script> tag (works over file:// where
 * fetch() is unavailable). This script does NOT modify data — it only wraps it.
 *
 *   data/nuclides.json            → data/nuclides-data.js            (NUCLIDE_DATA)
 *   data/effluent-scenario2.json  → data/effluent-scenario2-data.js  (EFFLUENT_S2_DATA)
 *
 * Usage:
 *   node tools/generate-data.js
 */

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', 'data');

const TARGETS = [
  {
    json: 'nuclides.json', js: 'nuclides-data.js', constName: 'NUCLIDE_DATA',
    summary: d => `Nuclides: ${d.nuclides.length}`,
  },
  {
    json: 'effluent-scenario2.json', js: 'effluent-scenario2-data.js', constName: 'EFFLUENT_S2_DATA',
    summary: d => `Scenario 2 nuclides: ${d.nuclides.map(n => n.id).join(', ')}`,
  },
];

try {
  for (const t of TARGETS) {
    const jsonPath = path.join(DATA_DIR, t.json);
    const jsPath = path.join(DATA_DIR, t.js);
    const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    const jsContent = `// Generated by tools/generate-data.js. Do not edit manually.
const ${t.constName} = ${JSON.stringify(data, null, 2)};
`;
    fs.writeFileSync(jsPath, jsContent, 'utf8');
    console.log(`✓ Generated ${jsPath} from ${jsonPath}`);
    console.log(`  ${t.summary(data)}`);
  }
} catch (err) {
  console.error(`✗ Error: ${err.message}`);
  process.exit(1);
}
