#!/usr/bin/env node

/**
 * generate-data.js — Wrap nuclides.json as JavaScript for offline compatibility
 *
 * Reads data/nuclides.json and outputs data/nuclides-data.js as a JavaScript module.
 * This script does NOT modify data — it only wraps JSON as const NUCLIDE_DATA.
 *
 * Usage:
 *   node tools/generate-data.js
 *
 * Output: data/nuclides-data.js
 */

const fs = require('fs');
const path = require('path');

const nuclideJsonPath = path.join(__dirname, '..', 'data', 'nuclides.json');
const jsPath = path.join(__dirname, '..', 'data', 'nuclides-data.js');

try {
  const jsonContent = fs.readFileSync(nuclideJsonPath, 'utf8');
  const nuclideData = JSON.parse(jsonContent);

  const jsContent = `// Generated by tools/generate-data.js. Do not edit manually.
const NUCLIDE_DATA = ${JSON.stringify(nuclideData, null, 2)};
`;

  fs.writeFileSync(jsPath, jsContent, 'utf8');
  console.log(`✓ Generated ${jsPath} from ${nuclideJsonPath}`);
  console.log(`  Nuclides: ${nuclideData.nuclides.length}`);
} catch (err) {
  console.error(`✗ Error: ${err.message}`);
  process.exit(1);
}
